#!/usr/bin/env ruby

require 'io/console'
require_relative 'lib/options'
require_relative 'lib/table_file'
require_relative 'lib/study_item'
require_relative 'lib/study_diary_methods'

include Options
include StudyDiaryMethods

REGISTER           = '1'
VIEW_NOT_CONCLUDED = '2'
SEARCH             = '3'
LIST_BY_CATEGORY   = '4'
DELETE             = '5'
MARK_AS_CONCLUDED  = '6'
VIEW_CONCLUDED     = '7'
OPTIONS            = '8'
EXIT               = '9'

$stdout.clear_screen

TableFile.new unless TableFile.exist?

puts 'Bem-vindo ao Diário de Estudos, seu companheiro para estudar!'

loop do
  puts <<~MENU
    [#{REGISTER}] Cadastrar um item para estudar
    [#{VIEW_NOT_CONCLUDED}] Ver todos os itens não concluídos
    [#{SEARCH}] Buscar um item de estudo
    [#{LIST_BY_CATEGORY}] Listar por categoria
    [#{DELETE}] Apagar um item
    [#{MARK_AS_CONCLUDED}] Marcar um item como concluído
    [#{VIEW_CONCLUDED}] Ver todos os itens concluídos
    [#{OPTIONS}] Opções
    [#{EXIT}] Sair
  MENU

  print 'Escolha uma opção: '
  option = gets.chomp

  case option
  when REGISTER           then StudyItem.register
  when VIEW_NOT_CONCLUDED then StudyItem.view_not_concluded
  when SEARCH             then StudyItem.search
  when LIST_BY_CATEGORY   then StudyItem.list_by_category
  when DELETE             then StudyItem.delete
  when MARK_AS_CONCLUDED  then StudyItem.mark_as_concluded
  when VIEW_CONCLUDED     then StudyItem.view_concluded
  when OPTIONS            then options
  when EXIT               then break
  else puts 'Opção inválida'
  end

  any_key_to_continue unless option == OPTIONS

  $stdout.clear_screen

  puts '============================================================='
end

puts 'Obrigado por usar o Diário de Estudos', ''

sleep(0.5)
